[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PLACEHOLDER"
version = "PLACEHOLDER_VERSION"
description = "RESEARCH PROJECT - FOR EDUCATIONAL PURPOSES ONLY - DO NOT INSTALL - PoC: Dependency confusion demonstration"
authors = [
    {name = "sec-lab"}
]
readme = "README.md"
requires-python = ">=3.4"

[project.urls]
Homepage = "https://dependency-confusion.sec-lab.it/"
Repository = "https://github.com/yourusername/multi-package"
Issues = "https://dependency-confusion.sec-lab.it/"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
